"""create senders and sender_aliases

Revision ID: 4f4215c931a1
Revises: f8db484c4301
Create Date: 2026-04-25 06:35:56.047773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f4215c931a1'
down_revision: Union[str, Sequence[str], None] = 'f8db484c4301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('senders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('group_key', sa.String(length=512), nullable=False),
    sa.Column('from_email', sa.String(length=320), nullable=False),
    sa.Column('from_domain', sa.String(length=255), nullable=False),
    sa.Column('list_id', sa.String(length=512), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('email_count', sa.Integer(), nullable=False),
    sa.Column('unsubscribe_http', sa.Text(), nullable=True),
    sa.Column('unsubscribe_mailto', sa.Text(), nullable=True),
    sa.Column('unsubscribe_one_click_post', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('active', 'unsubscribed', 'whitelisted', 'trashed', name='sender_status'), nullable=False),
    sa.Column('whitelist_scope', sa.Enum('none', 'sender', 'domain', name='whitelist_scope'), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'group_key', name='uq_sender_account_group')
    )
    with op.batch_alter_table('senders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_senders_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_senders_from_domain'), ['from_domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_senders_group_key'), ['group_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_senders_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_senders_status'), ['status'], unique=False)

    op.create_table('sender_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('from_email', sa.String(length=320), nullable=False),
    sa.Column('from_domain', sa.String(length=255), nullable=False),
    sa.Column('email_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['senders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sender_id', 'from_email', name='uq_alias_sender_email')
    )
    with op.batch_alter_table('sender_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sender_aliases_from_domain'), ['from_domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_sender_aliases_from_email'), ['from_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_sender_aliases_sender_id'), ['sender_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sender_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sender_aliases_sender_id'))
        batch_op.drop_index(batch_op.f('ix_sender_aliases_from_email'))
        batch_op.drop_index(batch_op.f('ix_sender_aliases_from_domain'))

    op.drop_table('sender_aliases')
    with op.batch_alter_table('senders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_senders_status'))
        batch_op.drop_index(batch_op.f('ix_senders_last_seen_at'))
        batch_op.drop_index(batch_op.f('ix_senders_group_key'))
        batch_op.drop_index(batch_op.f('ix_senders_from_domain'))
        batch_op.drop_index(batch_op.f('ix_senders_account_id'))

    op.drop_table('senders')
    # ### end Alembic commands ###
