"""create whitelist_rules

Revision ID: 64496324b848
Revises: 826ff8f72c6d
Create Date: 2026-04-25 06:54:38.110351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64496324b848'
down_revision: Union[str, Sequence[str], None] = '826ff8f72c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whitelist_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('sender', 'domain', 'mailbox', name='whitelist_kind'), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'kind', 'value', name='uq_whitelist_rule')
    )
    with op.batch_alter_table('whitelist_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whitelist_rules_account_id'), ['account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whitelist_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whitelist_rules_account_id'))

    op.drop_table('whitelist_rules')
    # ### end Alembic commands ###
